# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Excellent programme !
      labels:
        - Semver-Major
        - breaking-change
    - title: Other Changes
      labels:
        - "*"
